require_relative 'mutations/base'
require_relative 'mutations/scrapping/failure'
require_relative 'mutations/scrapping/success'
require_relative 'mutations/scrapping/start'
require_relative 'mutations/job_event/create'
