require_relative 'types/base_type'
require_relative 'types/site_type'
require_relative 'types/output_type'
require_relative 'types/schema_type'
require_relative 'types/task_type'
require_relative 'types/root_type'
require_relative 'types/mutation_type'
